/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowWorkflowIdRouteImport } from './routes/workflow.$workflowId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectSettingsProjectIdRouteImport } from './routes/project.settings.$projectId'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowWorkflowIdRoute = WorkflowWorkflowIdRouteImport.update({
  id: '/workflow/$workflowId',
  path: '/workflow/$workflowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSettingsProjectIdRoute =
  ProjectSettingsProjectIdRouteImport.update({
    id: '/project/settings/$projectId',
    path: '/project/settings/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/workflows': typeof WorkflowsRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/workflow/$workflowId': typeof WorkflowWorkflowIdRoute
  '/project/settings/$projectId': typeof ProjectSettingsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/project/$projectId'
    | '/workflow/$workflowId'
    | '/project/settings/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/project/$projectId'
    | '/workflow/$workflowId'
    | '/project/settings/$projectId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/workflows'
    | '/project/$projectId'
    | '/workflow/$workflowId'
    | '/project/settings/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  UpcomingRoute: typeof UpcomingRoute
  UsageRoute: typeof UsageRoute
  WorkflowsRoute: typeof WorkflowsRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  WorkflowWorkflowIdRoute: typeof WorkflowWorkflowIdRoute
  ProjectSettingsProjectIdRoute: typeof ProjectSettingsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$workflowId': {
      id: '/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof WorkflowWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/settings/$projectId': {
      id: '/project/settings/$projectId'
      path: '/project/settings/$projectId'
      fullPath: '/project/settings/$projectId'
      preLoaderRoute: typeof ProjectSettingsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  UpcomingRoute: UpcomingRoute,
  UsageRoute: UsageRoute,
  WorkflowsRoute: WorkflowsRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  WorkflowWorkflowIdRoute: WorkflowWorkflowIdRoute,
  ProjectSettingsProjectIdRoute: ProjectSettingsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
