/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as KhanbanRouteImport } from './routes/khanban'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectChecklistsProjectIdRouteImport } from './routes/project/checklists.$projectId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KhanbanRoute = KhanbanRouteImport.update({
  id: '/khanban',
  path: '/khanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectChecklistsProjectIdRoute =
  ProjectChecklistsProjectIdRouteImport.update({
    id: '/project/checklists/$projectId',
    path: '/project/checklists/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project/checklists/$projectId': typeof ProjectChecklistsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project/checklists/$projectId': typeof ProjectChecklistsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/settings': typeof SettingsRoute
  '/upcoming': typeof UpcomingRoute
  '/usage': typeof UsageRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/project/checklists/$projectId': typeof ProjectChecklistsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/khanban'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/project/$projectId'
    | '/project/checklists/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/khanban'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/project/$projectId'
    | '/project/checklists/$projectId'
  id:
    | '__root__'
    | '/'
    | '/khanban'
    | '/settings'
    | '/upcoming'
    | '/usage'
    | '/project/$projectId'
    | '/project/checklists/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhanbanRoute: typeof KhanbanRoute
  SettingsRoute: typeof SettingsRoute
  UpcomingRoute: typeof UpcomingRoute
  UsageRoute: typeof UsageRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  ProjectChecklistsProjectIdRoute: typeof ProjectChecklistsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khanban': {
      id: '/khanban'
      path: '/khanban'
      fullPath: '/khanban'
      preLoaderRoute: typeof KhanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/checklists/$projectId': {
      id: '/project/checklists/$projectId'
      path: '/project/checklists/$projectId'
      fullPath: '/project/checklists/$projectId'
      preLoaderRoute: typeof ProjectChecklistsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhanbanRoute: KhanbanRoute,
  SettingsRoute: SettingsRoute,
  UpcomingRoute: UpcomingRoute,
  UsageRoute: UsageRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  ProjectChecklistsProjectIdRoute: ProjectChecklistsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
