/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingRouteImport } from './routes/upcoming'
import { Route as QuickTasksRouteImport } from './routes/quickTasks'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as KhanbanRouteImport } from './routes/khanban'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'

const UpcomingRoute = UpcomingRouteImport.update({
  id: '/upcoming',
  path: '/upcoming',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickTasksRoute = QuickTasksRouteImport.update({
  id: '/quickTasks',
  path: '/quickTasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const KhanbanRoute = KhanbanRouteImport.update({
  id: '/khanban',
  path: '/khanban',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/projects': typeof ProjectsRoute
  '/quickTasks': typeof QuickTasksRoute
  '/upcoming': typeof UpcomingRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/projects': typeof ProjectsRoute
  '/quickTasks': typeof QuickTasksRoute
  '/upcoming': typeof UpcomingRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khanban': typeof KhanbanRoute
  '/projects': typeof ProjectsRoute
  '/quickTasks': typeof QuickTasksRoute
  '/upcoming': typeof UpcomingRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/khanban'
    | '/projects'
    | '/quickTasks'
    | '/upcoming'
    | '/project/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/khanban'
    | '/projects'
    | '/quickTasks'
    | '/upcoming'
    | '/project/$projectId'
  id:
    | '__root__'
    | '/'
    | '/khanban'
    | '/projects'
    | '/quickTasks'
    | '/upcoming'
    | '/project/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhanbanRoute: typeof KhanbanRoute
  ProjectsRoute: typeof ProjectsRoute
  QuickTasksRoute: typeof QuickTasksRoute
  UpcomingRoute: typeof UpcomingRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming': {
      id: '/upcoming'
      path: '/upcoming'
      fullPath: '/upcoming'
      preLoaderRoute: typeof UpcomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickTasks': {
      id: '/quickTasks'
      path: '/quickTasks'
      fullPath: '/quickTasks'
      preLoaderRoute: typeof QuickTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khanban': {
      id: '/khanban'
      path: '/khanban'
      fullPath: '/khanban'
      preLoaderRoute: typeof KhanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhanbanRoute: KhanbanRoute,
  ProjectsRoute: ProjectsRoute,
  QuickTasksRoute: QuickTasksRoute,
  UpcomingRoute: UpcomingRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
